puts "the students of villains academy"
puts "--------------"
puts "dr. hannibal lecter"
puts "darth vader"
puts "nurse ratched"
puts "micahel corleone"
puts "alex delarge"
puts "the wicked witch of the west"
puts "terminator"
puts "freddy krueger"
puts "the joker"
puts "joffrey baratheon"
puts "norman Bates"